### ISSUE TITLE
You may need to install appropriate plugins to handle the. hbs file format, or if it's an asset, add" * */*. hbs "to 'assetsInclude' in your configuration

### ISSUE THREAD

**Issue by LockingReal** [vituum/vite-plugin-handlebars#1]
Why do I use this plug-in? Vite will report "[vite] Internal server error: Failed to parse source for import analysis because the content contains invalid JS syntax. You may need to install appropriate plugins to handle the. hbs file format, or if it's an asset, add" * */*. hbs "to 'assetsInclude' in your configuration."

![image](https://user-images.githubusercontent.com/42457717/217227988-700b7495-754a-4d57-bedf-8c850459ca41.png)
![image](https://user-images.githubusercontent.com/42457717/217228065-6c69ee4f-092e-4b08-af7c-56855d33fb41.png)

**Comment by lubomirblazekcz** [comment]
You were using it wrong, input file should be `index.hbs.html` in `build.rollupOptions.input` or you should use it with https://vituum.dev/ defineConfig.

This should be better clear in 1.0
